### ISSUE TITLE
About WebVision statistics

### ISSUE THREAD

**Issue by z7d1** [Fahim-F/ManifoldDivideMix#1]
Thanks for your great work. You mentioned in the Introduction: "They reported that approximately 70% of the data is properly labeled, 5% have in-distribution noisy labels, and 25% have out-of-distribution noisy labels.". 

However, I did not find the source in paper "WebVision Database: Visual Learning and Understanding from Web Data". How did you get this data?

Looking forward to your reply!

**Comment by Fahim-F** [comment]
Thanks for your question.

As mentioned in Reference 2, they evaluated and reported the results. Here is the table from Reference 2.

![image](https://github.com/Fahim-F/ManifoldDivideMix/assets/12107979/f20e4ade-c44d-400b-82e3-231ce838bbd8)



Ref 2. Paul Albert, Diego Ortego, Eric Arazo, Noel O’Connor, and Kevin McGuinness. Addressing Out-of-Distribution Label Noise in Webly-Labelled Data. In Winter Conference on Applications of Computer Vision (WACV), 2022. 1, 2, 3, 4, 7

**Comment by z7d1** [comment]
Thank you very much for your reply!
